# Makefile to create pileups for downstream AI analysis
bamFolder=../bams
aiScript=ai_preprocessing.R
1KGSnps=/wsu/home/groups/piquelab/data/SNPs/1KG_SNPs_filt.011614.bed.gz
genome=/wsu/home/groups/piquelab/data/RefGenome/hg19.fa
transcriptFile=/wsu/home/groups/piquelab/data/RefTranscriptome/ensGene.hg19.v2.bed.gz

filtStr='$$4>0 && $$5 !~ /[^\^][<>]/ && $$5 !~ /\+[0-9]+[ACGTNacgtn]+/ && $$5 !~ /-[0-9]+[ACGTNacgtn]+/ && $$5 !~ /[^\^]\*/'
bedStr='{ print $$1,$$2-1,$$2,$$3,$$4,$$5,$$6}'

Qsub.ppn=2
Qsub.q=mmtxq
Qsub.N=pileup

.SECONDARY:

%.Qsub:
	touch $@
	echo "cd $${PWD}; make --file=Makefile1 $*" | qsub -q $(Qsub.q) -l nodes=1:ppn=$(Qsub.ppn) -N $(Qsub.N) -o $@ -e $@.e
	sleep 1;

%.pileup.gz: $(bamFolder)/%_clean.bam $(genome) $(1KGSnps)
	samtools mpileup -f $(genome) -l $(1KGSnps) $< | bgzip > $@

%.pileup.bed.gz: %.pileup.gz $(1KGSnps)
	less $< | awk $(filtStr) | awk -v OFS='\t' $(bedStr) | sortBed -i stdin | intersectBed -a stdin -b $(1KGSnps) -wo | gzip > $@

%.quasar.in.gz: %.pileup.bed.gz
	-R --vanilla --args $^ $@ < $(aiScript) 2> $@.e

all_pileups: $(patsubst $(bamFolder)/%_clean.bam,%.quasar.in.gz.Qsub,$(wildcard $(bamFolder)/*_clean.bam))

counts_all: $(patsubst $(bamFolder)/%.bam,%.transcripts.gz,$(wildcard $(bamFolder)/*.bam))

clean:
	rm *.pileup.gz
	rm *.pileup.bed.gz
	rm *.pileup.clean.bed.gz
	rm *.transcripts.gz


